"use client";
import React from "react";
import { MdFileDownload } from "react-icons/md";
import { FaSearch } from "react-icons/fa";
import { FaCheck } from "react-icons/fa";
const Instruction = () => {
  return (
    <div className="w-full mt-[20px] bg-muted/20 flex justify-center items-center mb-[100px]">
      <div className="px-[20px] w-[min(1400px , 85%)] py-[70px] flex  flex-col justify-center gap-[40px]">

        <div className="flex relative w-[min(1350px,79vw)] z-[0] border-[3px] rounded-[16px] flex-col">
          <div className="w-full h-[50px]"></div>
          <div className="relative bg-[#0f0e10] z-[10000] px-[100px]  w-[105%] min-h-[90px] left-[-30px] flex justify-between items-end">
            <h1 className="text-4xl font-[470]">Upload</h1> 
            <h2  className="text-md max-w-[50%] font-[500]">Choose a video file that you want to analyze and upload it in the
            "Detection" section. The videos should be within 20-30 MB in size
            and should be in MP4 format</h2>
          </div>
          <div className="w-full h-[50px]"></div>
        </div>

        <div className="flex relative w-[min(1250px,79vw)] z-[0] border-[3px] rounded-[16px] flex-col">
          <div className="w-full h-[50px]"></div>
          <div className="relative bg-[#0f0e10] z-[10000] px-[100px]  w-[105%] min-h-[90px] left-[-30px] flex justify-between items-end">
          <h1 className="text-4xl font-[470]">AI Analysis</h1> 
            <h2  className="text-md max-w-[50%] font-[500]">The uploaded videos undergo thorough analysis by AI algorithms to detect any signs of manipulation or deepfake content.</h2> 
          </div>
          <div className="w-full h-[50px]"></div>
        </div>


        <div className="flex relative w-[min(1250px,79vw)] z-[0] border-[3px] rounded-[16px] flex-col">
          <div className="w-full h-[50px]"></div>
          <div className="relative bg-[#0f0e10] z-[10000] px-[100px]  w-[105%] min-h-[90px] left-[-30px] flex justify-between items-end">
          <h1 className="text-4xl font-[470]">Report Review</h1> 
            <h2 className="text-md max-w-[50%] font-[500]">Users receive detailed reports generated by the AI analysis, enabling them to review and interpret the findings to assess the authenticity of the video content. </h2>  
          </div>
          <div className="w-full h-[50px]"></div>
        </div>


        {/* <div className="flex  items-center flex-col gap-4 max-w-[350px]">
          <div className="bg-primary rounded-full w-16 h-16 flex justify-center items-center transition duration-500 ease hover:rotate-360 hover:scale-110">
            <FaSearch size={30} color="white" className="icon" />
          </div>
          <p className="text-center">
            Click on "Detect Videos" and wait for some time, as the
            identification process can take 1 or 2 minutes, until the output
            result comes. You can play some games related to deepfake.
          </p>
        </div>
        <div className="flex  items-center flex-col gap-4 max-w-[350px]">
          <div className="bg-primary rounded-full w-16 h-16 flex justify-center items-center transition duration-500 ease hover:rotate-360 hover:scale-110">
            <FaCheck size={12} color="white" className="icon w-10 h-10" />
          </div>
          <p className="text-center">
            After the prediction, you will find out whether your video is fake
            or real. In the output, we provide some metrics, including the
            percentage for different techniques used, separate results for eye
            blinking, face masking, and lip syncing, and finally, the overall
            result.
          </p>
        </div> */}
      </div>
    </div>
  );
};

export default Instruction;
